[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['cd frontend && pnpm install --frozen-lockfile']

[phases.build]
cmds = ['cd frontend && pnpm run build']

[start]
cmd = 'cd frontend && pnpm start'